version: '3'

networks:
  webapp:

services:


  web:
    image: nginx:1.23-alpine
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./:/www:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - app
    networks:
      - webapp


  app:
    image: rcsnjszg/laravelapp:0.0.1-alpine
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    volumes:
      - ./:/www:rw
      # - ./docker/php/home:/home/phpdocker:rw
    networks:
      - webapp


  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password --sql-mode="ANSI_QUOTES"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - TZ="${TZ}"
    ports:
      - "${DB_PUBLIC_PORT}:3306"
    volumes:
      - "./docker/mysql/var/lib/mysql:/var/lib/mysql:rw"
    networks:
      - webapp


  phpmyadmin:
    image: phpmyadmin:5.1-apache
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${DB_HOST}
      # - PMA_PORT=${DB_PORT}
      # - PMA_USER=${DB_USERNAME}
      # - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    volumes:
      - ./docker/phpmyadmin/config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - webapp